variables:
    PWD: $PWD
    CI_DIR: ./
    CI_PRIMARY: /
    DOCKER_REGISTRY: $DOCKER_USER
    DOCKER_CREDENTIAL: $DOCKER_CREDENTIAL
    DOCKER_USER: $DOCKER_USER
    TAG_IMAGE: "v0.0.1" 
  
stages:
    - docker

.template_docker: &template_docker
    stage: docker
    image: wedneyyuri/awscli-dind
    services:
        - docker:18.09-dind
    script:
        - docker login --username=$DOCKER_USER --password=$PASSWORD
        - cd docker/
        - export TAG=${CI_COMMIT_SHORT_SHA}
        - docker build -t ${DOCKER_REGISTRY}/${SERVICE}:${TAG_IMAGE} -f ${DOCKERFILE} ..
        - docker push ${DOCKER_REGISTRY}/${SERVICE}:${TAG_IMAGE}
  
dev:build:docker:
    <<: *template_docker
    only:
      - main
    variables:
      PASSWORD: $DOCKER_CREDENTIAL  
      DOCKER_REGISTRY: $DOCKER_USER
      DOCKERFILE: Dockerfile
      SERVICE: "potency"
