variables:
    PWD: $PWD
    DOCKER_REGISTRY: $DOCKER_USER
    DOCKER_CREDENTIAL: $DOCKER_CREDENTIAL
    DOCKER_USER: $DOCKER_USER
    TAG_IMAGE: "v0.0.1"
    HELM_REPO: $HELM_REPO 
  
stages:
    - docker
    - package
    - deploy

.template_docker: &template_docker
    stage: docker
    image: wedneyyuri/awscli-dind
    services:
        - docker:18.09-dind
    script:
        - docker login --username=$DOCKER_USER --password=$PASSWORD
        - cd docker/
        - export TAG=${CI_COMMIT_SHORT_SHA}
        - docker build -t ${DOCKER_REGISTRY}/${SERVICE}:${TAG_IMAGE} -f ${DOCKERFILE} ..
        - docker push ${DOCKER_REGISTRY}/${SERVICE}:${TAG_IMAGE}

.template_helm: &template_helm
    stage: package
    image: alpine/helm
    script:
      - helm install -f ./infra/helm/app-potency/values.yaml ${ENV}-${SERVICE} ./infra/helm/app-potency/
      
dev:build:docker:
    <<: *template_docker
    only:
      - main
    variables:
      PASSWORD: $DOCKER_CREDENTIAL  
      DOCKER_REGISTRY: $DOCKER_USER
      DOCKERFILE: Dockerfile
      SERVICE: "potency"

dev:package:helm:
  <<: *template_helm
  only:
    - main
  variables:
    HELM_REPO: $HELM_REPO  
  script:
    - cd infra/helm/app-potency
    - helm package app-potency
    - helm repo index --url ${HELM_REPO}

dev:deploy:helm:
    stage: deploy
    image: alpine/helm
    only:
      - main
    variables:
      ENV: "dev"
      SERVICE: "potency"
    